version: "3.8"

services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_DB: gx_seletivo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - app-network
    volumes:
      - minio-data:/data
  tomcat11:
      image: tomcat:11-jdk17
      container_name: seletivo-tomcat
      ports:
        - "8080:8080"
      volumes:
        - ./tomcat/webapps:/usr/local/tomcat/webapps
        - ./tomcat/conf/context.xml:/usr/local/tomcat/conf/context.xml
      depends_on:
        - postgres
      networks:
        - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
  minio-data:
