openapi: 3.0.0
info:
  title: "autenticar"
  description: "autenticar"
  version: "20250331024554"
servers:
  - url: http://localhost:8080/seletivojava/api/autenticar
paths:
  /login:
    post:
      tags:
        - api  
      operationId: "api.autenticar.Login"
      summary: "Método gerar o token jwt"
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginInput"
      
      responses:
        200:
          description: "Successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginOutput"
        404:
          description: "Not found"

components:
  schemas:
    LoginOutput:
      properties:
        Token:
          type: "string"
        Messages:
          description: "Messages"
          type: array
          items:
            $ref: "#/components/schemas/GeneXus.Common.Messages_Message"

    LoginInput:  
      properties:
        Login:
          type: "string"
        Password:
          type: "string"
  
    GeneXus.Common.Messages_Message:
      properties:
        Id:
          description: "Id"
          type: "string"
        Type:
          description: "Type"
          type: "integer"
          format: "int32"
        Description:
          description: "Description"
          type: "string"



 
